apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: u7eo8koiz-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: u7eo8koiz-python 
  name: u7eo8koiz-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: u7eo8koiz-python 
