apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: u7eo8koiz-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: rhtap-quay-quay-rhtap-quay.apps.rosa.kx-9cdd7e0841.8yp1.p3.openshiftapps.com/rhtap/rhtap-qe:7cc6541393932c0715ea2048f3b8dad87f799afe@sha256:e5bebcebf744158d27803173559a87b7053b75821d218bb49d2fc007110b090f
          name: container-image
